### ISSUE TITLE
Hangs in terminating a running container

### ISSUE THREAD

**Issue by adrysn** [lablup/backend.ai-agent#113]
Terminating a running kernel does not finish. This will raise timeout error in manager side.

```
Traceback (most recent call last):
  File "/Users/adrysn/Develop/backend.ai/backend.ai-dev/manager/src/ai/backend/gateway/kernel.py", line 331, in destroy
    last_stat = await registry.destroy_session(sess_id, owner_access_key)
  File "/Users/adrysn/Develop/backend.ai/backend.ai-dev/manager/src/ai/backend/manager/registry.py", line 788, in destroy_session
    return last_stat
  File "/Users/adrysn/.pyenv/versions/manager/lib/python3.6/site-packages/aiotools/context.py", line 115, in __aexit__
    await self._agen.athrow(exc_type, exc_value, tb)
  File "/Users/adrysn/Develop/backend.ai/backend.ai-dev/manager/src/ai/backend/manager/registry.py", line 177, in handle_kernel_exception
    raise exc_class('TIMEOUT') from None
ai.backend.gateway.exceptions.KernelDestructionFailed: 500 Internal Server Error
```

The cause of the error is probably related to setting asyncio event lock in [this line](https://github.com/lablup/backend.ai-agent/blob/master/src/ai/backend/agent/server.py#L1297). `stat_sync_states[cid].terminated.wait()` is not `set` forever, which blocks further code execution.

**Comment by adrysn** [comment]
I don't know this is complete fix, but it fixes indefinite hang when destroying a container in Mac currently.

* There was no logic to signal from container to agent that it is terminated in Mac API. I think this is why agent server hangs when destroying a container, since it did not receive that the container is killed or not.
* If a container is destroyed just after its creation, there may be no time to report the container usage stats to Redis server. In that case, an uncaught exception (`UnboundLocalError`) is raised when collecting last stat of a container (in `collect_container_stat` function).

**Comment by achimnol** [comment]
Fixed by splitting `trigger_and_wait_collection()` in the stat sync process (formerly stat collector deamon) into two separate steps: `collect-stat` and `terminated` — see 21ec222.
In the cgroup mode, the stat sync process makes the agent to collect statistics once more before handling termination while it doesn't so in the API mode.

Still, immediate termination of a container may loose its statistics in the API mode and in this case the `last_stat` becomes an empty dictionary. Though in my tests, as long as the container launches without crashing and execute some Python code (e.g., hello world), at least one stat collection happens.
